# Copyright 2024 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

name: Go Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.12-dind
        ports:
          - 2375:2375
          - 9094:9094
          - 27017:27017

    steps:
    - name: Checkout code
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

    - name: Set up Go
      uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4
      with:
        go-version-file: go.mod

    - name: Run go test
      env:
        KAFKA_HOST: localhost:9094
        KAFKA_IMAGE: bitnamilegacy/kafka
        KAFKA_TAG: 3.4.1
        MONGO_HOST: localhost:27017
        MONGO_IMAGE: mongo
        MONGO_TAG: 7.0.5-rc0
      run: go test -v ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

    - name: Prepare archive
      run: mkdir -p ./out/reports ./out/badges

    - name: Generate coverage report
      run: go tool cover -html=cover.out -o=./out/reports/coverage-report.html

    - name: Check test coverage
      uses: vladopajic/go-test-coverage@f190f667e23b4441202d0bab0f8c2e7bce8925b6 # v2
      with:
        profile: cover.out
        local-prefix: github.com/telekom/pubsub-horizon-vortex
        badge-file-name: ./out/badges/coverage.svg
        git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
        git-branch: badges

    - name: Archive artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: artifacts
        path: ./out/**